In [2]:
import tensorflow as tf
import numpy as np

In [5]:
n_inputs = 3 
n_neurons = 5

X0 = tf.placeholder(tf.float32, [None, n_inputs]) 
X1 = tf.placeholder(tf.float32, [None, n_inputsxuts])

Wx = tf.Variable(tf.random_normal(shape=[n_inputs, n_neurons],dtype=tf.float32)) 
Wy = tf.Variable(tf.random_normal(shape=[n_neurons,n_neurons],dtype=tf.float32)) 
b = tf.Variable(tf.zeros([1, n_neurons], dtype=tf.float32))

Y0 = tf.tanh(tf.matmul(X0, Wx) + b)
Y1 = tf.tanh(tf.matmul(Y0, Wy) + tf.matmul(X1, Wx) + b)



In [12]:
# Mini-batch:        instance 0,instance 1,instance 2,instance 3
X0_batch = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 0, 1]]) # t = 0 
X1_batch = np.array([[9, 8, 7], [0, 0, 0], [6, 5, 4], [3, 2, 1]]) # t = 1

init = tf.global_variables_initializer()

with tf.Session() as sess: 
    init.run()
    Y0_val, Y1_val = sess.run([Y0, Y1], feed_dict={X0: X0_batch, X1: X1_batch})
    print(Y0_val)
    print(Y1_val)

[[-0.65358448  0.99962282 -0.27225947  0.09576805  0.43423074]
 [ 0.93852603  1.          0.69045711  0.89166325 -0.98711091]
 [ 0.99957871  1.          0.96236318  0.99208212 -0.9999668 ]
 [ 0.99999857  0.99999797  0.49476323  0.99995953 -1.        ]]
[[ 1.          1.          0.9996174   0.99964309 -1.        ]
 [-0.9993962   0.98694068 -0.9417454   0.98890853  0.69370204]
 [ 0.84572172  1.          0.61191118  0.99996853 -0.99998677]
 [-0.61480904  0.99999982 -0.45726639  0.99933571 -0.97197151]]
